# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Shared fixtures for Kubernetes module tests.

Heavy lifting lives in ``tests.harness.k8s``; this file exposes those
builders as pytest fixtures and re-exports helper functions for backward
compatibility with direct imports from test files.
"""

from pathlib import Path
from typing import Any

import pytest

from tests.harness.k8s import (
    build_completed_jobset,
    build_failed_jobset,
    build_mock_api,
    build_running_jobset,
    build_sample_config,
    build_sample_jobset,
    build_sample_pod_template,
    build_sample_run,
    create_api_exception,
    create_jobset_list_response,
    patch_api_accessors,
)

# Re-export helper functions so existing ``from tests.unit.kubernetes.conftest import ...``
# statements continue to work without changes.
__all__ = [
    "create_api_exception",
    "create_jobset_list_response",
    "patch_api_accessors",
]


# =============================================================================
# Helm chart guard
# =============================================================================
# The ``aiperf-operator`` Helm chart (and the CRD manifests it carries) is
# generated by the operator port, not by this package.

OPERATOR_CHART_DIR = (
    Path(__file__).resolve().parents[3] / "deploy" / "helm" / "aiperf-operator"
)

requires_operator_chart = pytest.mark.skipif(
    not OPERATOR_CHART_DIR.exists(),
    reason="deploy/helm/aiperf-operator not present",
)


# =============================================================================
# Mock ApiClient Fixtures
# =============================================================================


@pytest.fixture
def mock_api():
    """Mock kubernetes_asyncio ApiClient."""
    return build_mock_api()


# =============================================================================
# Sample Data Fixtures
# =============================================================================


@pytest.fixture
def sample_jobset() -> dict[str, Any]:
    """Create a sample JobSet dict for testing."""
    return build_sample_jobset()


@pytest.fixture
def sample_running_jobset(sample_jobset) -> dict[str, Any]:
    """Create a sample running JobSet."""
    return build_running_jobset(sample_jobset)


@pytest.fixture
def sample_completed_jobset(sample_jobset) -> dict[str, Any]:
    """Create a sample completed JobSet."""
    return build_completed_jobset(sample_jobset)


@pytest.fixture
def sample_failed_jobset(sample_jobset) -> dict[str, Any]:
    """Create a sample failed JobSet."""
    return build_failed_jobset(sample_jobset)


# =============================================================================
# Config Fixtures
# =============================================================================


@pytest.fixture
def sample_config():
    """Create a minimal AIPerfConfig for testing."""
    return build_sample_config()


@pytest.fixture
def sample_run(sample_config):
    """Create a minimal BenchmarkRun for testing."""
    return build_sample_run(sample_config)


@pytest.fixture
def sample_pod_template():
    """Create a sample PodTemplateConfig for testing."""
    return build_sample_pod_template()
