# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: aiperf-operator
description: AIPerf Kubernetes Operator for LLM inference benchmarking
type: application
kubeVersion: ">=1.24.0-0"
version: 0.7.0
appVersion: "0.13.0"
keywords:
  - aiperf
  - llm
  - benchmarking
  - inference
  - nvidia
home: https://github.com/nvidia/aiperf
maintainers:
  - name: NVIDIA
